### ISSUE TITLE
Fails to build with kddockwidgets-2.0.0: error: no viable conversion from 'const QVector<KDDockWidgets::Core::DockWidget *>' to 'const QVector<KDDockWidgets::DockWidgetBase *>'

### ISSUE THREAD

**Issue by yurivict** [KDAB/hotspot#569]
**Describe the bug**
```
wrkdirs/usr/ports/devel/hotspot/work/hotspot-1.4.1/src/mainwindow.cpp:265:36: error: no viable conversion from 'const QVector<KDDockWidgets::Core::DockWidget *>' to 'const QVector<KDDockWidgets::DockWidgetBase *>'
    m_resultsPage->initDockWidgets(restored);
                                   ^~~~~~~~
/usr/local/include/qt5/QtCore/qvector.h:72:12: note: candidate constructor not viable: no known conversion from 'const Vector<Core::DockWidget *>' (aka 'const QVector<KDDockWidgets::Core::DockWidget *>') to 'const QVector<KDDockWidgets::DockWidgetBase *> &' for 1st argument
    inline QVector(const QVector<T> &v);
           ^
/usr/local/include/qt5/QtCore/qvector.h:75:5: note: candidate constructor not viable: no known conversion from 'const Vector<Core::DockWidget *>' (aka 'const QVector<KDDockWidgets::Core::DockWidget *>') to 'QVector<KDDockWidgets::DockWidgetBase *> &&' for 1st argument
    QVector(QVector<T> &&other) noexcept : d(other.d) { other.d = Data::sharedNull(); }
    ^
/usr/local/include/qt5/QtCore/qvector.h:79:12: note: candidate constructor not viable: no known conversion from 'const Vector<Core::DockWidget *>' (aka 'const QVector<KDDockWidgets::Core::DockWidget *>') to 'std::initializer_list<DockWidgetBase *>' for 1st argument
    inline QVector(std::initializer_list<T> args);
           ^
/usr/local/include/qt5/QtCore/qvector.h:70:14: note: explicit constructor is not a candidate
    explicit QVector(int size);
             ^
/usr/local/include/qt5/QtCore/qvector.h:83:14: note: explicit constructor is not a candidate
    explicit QVector(QArrayDataPointerRef<T> ref) noexcept : d(ref.ptr) {}
             ^
/wrkdirs/usr/ports/devel/hotspot/work/hotspot-1.4.1/src/resultspage.h:55:73: note: passing argument to parameter 'restored' here
    void initDockWidgets(const QVector<KDDockWidgets::DockWidgetBase*>& restored);
                                                                        ^
1 error generated.
```

Version: 1.4.1
clang-16
FreeBSD 13.2
