### PR TITLE
add support for reading compress perf files

### LINKED ISSUE #331: Allow reading of gz/lz compressed perf data
**Is your feature request related to a problem? Please describe.**
Perf data, especially if not created with `-z` can get quite huge fast, for sharing/later comparisons those may be externally compressed. It is always extra work to unpack those (also to remind oneself to delete those uncompressed files later)

**Describe the solution you'd like**
Open Dialog may also include `*perf.data.gz`, `*perf.data.lz`, `*perf.gz`, `*perf.lz` and compress those either in-memory or as temporary file, loading that (and delete it upon close).

**Describe alternatives you've considered**
Stick to manual handling.

### PR DESCRIPTION
**Pull request by lievenhey**
use karchive to open compressed perf data and write it into an temporary
file to feed the perfparser with it

closes #331

### CODE REVIEW

**Comment by GitMensch** [comment]
Code looks good, the only part missing seems to be the file open dialog.

**Comment by lievenhey** [comment]
> Code looks good, the only part missing seems to be the file open dialog.

the file dialog has a filter for perf.data.* so no changes are needed

**Comment by GitMensch** [comment]
Looks like all requests were resolved :-) Thanks for the work!

**Comment by fake-name** [comment]
Does this require a specific version of KArchive?

Trying to build with `Depends: libkf5archive5 (= 5.80.0-0ubuntu1~18.04.sav0), qtbase5-dev (>= 5.14.0~)`, it fails:

```
[ 48%] Building CXX object 3rdparty/CMakeFiles/hotspot-perfparser.dir/perfparser/app/perfsymboltable.cpp.o
/home/durr/hotspot/src/parsers/perf/perfparser.cpp: In member function ‘QString PerfParser::decompressIfNeeded(const QString&)’:
/home/durr/hotspot/src/parsers/perf/perfparser.cpp:1854:43: error: no matching function for call to ‘KCompressionDevice::KCompressionDevice(const QString&)’
 1854 |     KCompressionDevice compressedFile(path);
      |                                           ^
In file included from /usr/include/KF5/KArchive/KCompressionDevice:1,
                 from /home/durr/hotspot/src/parsers/perf/perfparser.cpp:36:
/usr/include/KF5/KArchive/kcompressiondevice.h:54:5: note: candidate: ‘KCompressionDevice::KCompressionDevice(const QString&, KCompressionDevice::CompressionType)’
   54 |     KCompressionDevice(const QString &fileName, CompressionType type);
      |     ^~~~~~~~~~~~~~~~~~
/usr/include/KF5/KArchive/kcompressiondevice.h:54:5: note:   candidate expects 2 arguments, 1 provided
/usr/include/KF5/KArchive/kcompressiondevice.h:47:5: note: candidate: ‘KCompressionDevice::KCompressionDevice(QIODevice*, bool, KCompressionDevice::CompressionType)’
   47 |     KCompressionDevice(QIODevice *inputDevice, bool autoDeleteInputDevice, CompressionType type);
      |     ^~~~~~~~~~~~~~~~~~
/usr/include/KF5/KArchive/kcompressiondevice.h:47:5: note:   candidate expects 3 arguments, 1 provided
[ 48%] Building CXX object 3rdparty/CMakeFiles/hotspot-perfparser.dir/perfparser/app/perfelfmap.cpp.o
[ 49%] Building CXX object 3rdparty/CMakeFiles/hotspot-perfparser.dir/perfparser/app/perfkallsyms.cpp.o
[ 49%] Building CXX object 3rdparty/CMakeFiles/hotspot-perfparser.dir/perfparser/app/perfaddresscache.cpp.o
[ 49%] Building CXX object 3rdparty/CMakeFiles/hotspot-perfparser.dir/perfparser/app/perftracingdata.cpp.o
tests/integrationtests/CMakeFiles/tst_perfparser.dir/build.make:145: recipe for target 'tests/integrationtests/CMakeFiles/tst_perfparser.dir/__/__/src/parsers/perf/perfparser.cpp.o' failed
make[2]: *** [tests/integrationtests/CMakeFiles/tst_perfparser.dir/__/__/src/parsers/perf/perfparser.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object 3rdparty/CMakeFiles/hotspot-perfparser.dir/perfparser/app/perfdwarfdiecache.cpp.o
[ 50%] Building CXX object 3rdparty/CMakeFiles/hotspot-perfparser.dir/perfparser/app/demangler.cpp.o
[ 51%] Linking CXX executable ../lib/x86_64-linux-gnu/libexec/hotspot-perfparser
[ 51%] Built target hotspot-perfparser
CMakeFiles/Makefile2:2638: recipe for target 'tests/integrationtests/CMakeFiles/tst_perfparser.dir/all' failed
make[1]: *** [tests/integrationtests/CMakeFiles/tst_perfparser.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
durr@rosbox18:~/build-hotspot$ 
```

There is no version specified in the the CMakeLists `require()` invocation.
