### ISSUE TITLE
Build error with latest master

### ISSUE THREAD

**Issue by erijo** [KDAB/hotspot#212]
The latest master (7f9a5e9a509b) fails to build on Debian unstable (Qt 5.11.3):

```
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QVector:1,
                 from /home/erik/source/hotspot/3rdparty/perfparser/app/perfelfmap.h:24,
                 from /home/erik/source/hotspot/3rdparty/perfparser/app/perfaddresscache.h:24,
                 from /home/erik/source/hotspot/3rdparty/perfparser/app/perfsymboltable.h:28,
                 from /home/erik/source/hotspot/3rdparty/perfparser/app/perfsymboltable.cpp:26:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h: In instantiation of ‘void QVector<T>::reallocData(int, int, QArrayData::AllocationOptions) [with T = CuDieRanges::CuDieRange; QArrayData::AllocationOptions = QFlags<QArrayData::AllocationOption>]’:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:681:9:   required from ‘void QVector<T>::append(const T&) [with T = CuDieRanges::CuDieRange]’
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:260:41:   required from ‘void QVector<T>::push_back(const T&) [with T = CuDieRanges::CuDieRange]’
/home/erik/source/hotspot/3rdparty/perfparser/app/perfsymboltable.cpp:712:39:   required from here
/usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:606:33: error: no matching function for call to ‘CuDieRanges::CuDieRange::CuDieRange()’
  606 |                                 new (dst++) T();
      |                                 ^~~~~~~~~~~~~~~
/home/erik/source/hotspot/3rdparty/perfparser/app/perfsymboltable.cpp:672:9: note: candidate: ‘CuDieRanges::CuDieRange::CuDieRange(Dwarf_Die*, Dwarf_Addr)’
  672 |         CuDieRange(Dwarf_Die *die, Dwarf_Addr bias)
      |         ^~~~~~~~~~
/home/erik/source/hotspot/3rdparty/perfparser/app/perfsymboltable.cpp:672:9: note:   candidate expects 2 arguments, 0 provided
/home/erik/source/hotspot/3rdparty/perfparser/app/perfsymboltable.cpp:670:12: note: candidate: ‘constexpr CuDieRanges::CuDieRange::CuDieRange(const CuDieRanges::CuDieRange&)’
  670 |     struct CuDieRange
      |            ^~~~~~~~~~
/home/erik/source/hotspot/3rdparty/perfparser/app/perfsymboltable.cpp:670:12: note:   candidate expects 1 argument, 0 provided
/home/erik/source/hotspot/3rdparty/perfparser/app/perfsymboltable.cpp:670:12: note: candidate: ‘constexpr CuDieRanges::CuDieRange::CuDieRange(CuDieRanges::CuDieRange&&)’
/home/erik/source/hotspot/3rdparty/perfparser/app/perfsymboltable.cpp:670:12: note:   candidate expects 1 argument, 0 provided
```

I get the same error if I try to build perfparser separately.

**Comment by erijo** [comment]
g++ (Debian 9.2.1-8) 9.2.1 20190909

**Comment by milianw** [comment]
can you please check with the latest and don't forget to run `perf submodule update` - the code looks different from what you are seeing:

```

    struct CuDieRange
    {
        Dwarf_Die *cuDie;
        Dwarf_Addr bias;
        Dwarf_Addr low;
        Dwarf_Addr high;

        bool contains(Dwarf_Addr addr) const
        {
            return low <= addr && addr < high;
        }
    };
```

**Comment by erijo** [comment]
Did you forget to push perfparser? This link on GitHub doesn't work: https://github.com/KDAB/perfparser/compare/49decbe1d1f46be49b94c8adf54e5077d22e0228...5990b549e8779f02a75a3781e20ec7030c1fe4ae

**Comment by milianw** [comment]
I did indeed, can you try again please?

**Comment by erijo** [comment]
Now it builds, thanks!
